backend:
  name: github
  repo: tomsza26/tymekNetlify
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/pages/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-post',
        }
      - { label: 'Tytuł', name: 'title', widget: 'string' }
      - {
          label: 'Data publikacji',
          name: 'date',
          widget: 'datetime',
          dateFormat: 'DD.MM.YYYY',
          timeFormat: false,
        }
      - { label: 'Obrazek postu', name: 'featuredimage', widget: image }
      - { label: 'Treść', name: 'body', widget: 'markdown' }
      - {
          label: 'Kategoria',
          name: 'category',
          widget: 'select',
          options:
            [
              'DIETA',
              'TRENING',
              'CIEKAWOSTKI',
              'JAK ZACZĄĆ?',
              'ROZWÓJ OSOBISTY',
              'PLANY TRENINGOWE',
            ],
        }

  - name: 'people'
    label: 'Metamorfozy'
    folder: 'src/pages/metamorfozy'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'people',
        }
      - { label: 'Imię i nazwisko', name: 'title', widget: 'string' }
      - { label: 'Data publikacji', name: 'date', widget: 'datetime' }
      - { label: 'Opis', name: 'body', widget: 'text' }
      - {
          label: 'Osiągnięto',
          name: 'achieved',
          widget: text,
          dateFormat: 'DD.MM.YYYY',
          timeFormat: false,
        }
      - { label: 'Czas przemiany', name: 'transformTime', widget: 'text' }
      - { label: 'Obraz przed', name: 'imageBefore', widget: image }
      - { label: 'Obraz po', name: 'imageAfter', widget: image }

  - name: 'oMnie'
    label: 'O Mnie'
    folder: 'src/pages'
    create: false
    delete: false
    identifier_field: Title
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'o-mnie',
        }
      - { label: 'Tytuł', name: 'title', widget: 'string' }
      - { label: 'Opis', name: 'body', widget: 'markdown' }

  - name: 'Wspolpraca'
    delete: false
    label: 'Współpraca'
    folder: 'src/pages'
    identifier_field: Title
    create: false
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'wspolpraca',
        }
      - { label: 'Tytuł', name: 'title', widget: 'string' }
      - { label: 'Opis', name: 'body', widget: 'markdown' }
